if(NOT DEFINED PANELIST_SOURCE_DIR)
  message(FATAL_ERROR "PANELIST_SOURCE_DIR is not defined")
endif()

if(NOT DEFINED PANELIST_BINARY_DIR)
  message(FATAL_ERROR "PANELIST_BINARY_DIR is not defined")
endif()

if(NOT DEFINED PANELIST_GENERATED_INCLUDE_DIR)
  message(FATAL_ERROR "PANELIST_GENERATED_INCLUDE_DIR is not defined")
endif()

if(NOT DEFINED PANELIST_PACKAGE_NAME)
  message(FATAL_ERROR "PANELIST_PACKAGE_NAME is not defined")
endif()

if(NOT DEFINED PANELIST_PACKAGE_FILE)
  message(FATAL_ERROR "PANELIST_PACKAGE_FILE is not defined")
endif()

set(PANELIST_DOC_DIR "${PANELIST_BINARY_DIR}/docs/html")
if(NOT EXISTS "${PANELIST_DOC_DIR}/index.html")
  message(FATAL_ERROR "Doxygen HTML documentation was not generated")
endif()

set(PANELIST_VERSION_HEADER
    "${PANELIST_GENERATED_INCLUDE_DIR}/panelist/panelist_version.hpp")
if(NOT EXISTS "${PANELIST_VERSION_HEADER}")
  message(FATAL_ERROR "Configured Panelist version header was not generated")
endif()

set(PANELIST_STAGE_PARENT "${PANELIST_BINARY_DIR}/package")
set(PANELIST_STAGE_DIR "${PANELIST_STAGE_PARENT}/${PANELIST_PACKAGE_NAME}")

file(REMOVE_RECURSE "${PANELIST_STAGE_DIR}")
file(MAKE_DIRECTORY "${PANELIST_STAGE_DIR}")

file(COPY "${PANELIST_SOURCE_DIR}/include" DESTINATION "${PANELIST_STAGE_DIR}")
file(COPY "${PANELIST_GENERATED_INCLUDE_DIR}/"
     DESTINATION "${PANELIST_STAGE_DIR}/include")
file(MAKE_DIRECTORY "${PANELIST_STAGE_DIR}/doc")
file(COPY "${PANELIST_DOC_DIR}/" DESTINATION "${PANELIST_STAGE_DIR}/doc")

file(REMOVE "${PANELIST_PACKAGE_FILE}")
file(
  ARCHIVE_CREATE
  OUTPUT "${PANELIST_PACKAGE_FILE}"
  PATHS "${PANELIST_PACKAGE_NAME}"
  FORMAT gnutar
  COMPRESSION GZip
  WORKING_DIRECTORY "${PANELIST_STAGE_PARENT}")

message(STATUS "Created ${PANELIST_PACKAGE_FILE}")
